import { z } from "zod";

export const Person = z.object({
  company_record_id: z.string().nullable(),
  company_table_id: z.string(),
  domain: z.string(),
  first_name: z.string(),
  company_first_slug: z.string(),
  last_name: z.string(),
  latest_experience_company: z.string(),
  latest_experience_title: z.string(),
  latest_experience_start_date: z.string(),
  location_name: z.string(),
  name: z.string(),
  profile_id: z.string(),
  url: z.string().nullable(),
});
export type Person = z.infer<typeof Person>;

export const FindPeopleResult = z.object({
  result: z.object({
    people: z.array(Person),
    peopleCount: z.number(),
  }),
  metadata: z.object({
    textPreview: z.string(),
    imagePreview: z.string(),
    logInfo: z.object({
      requestId: z.string(),
      groupName: z.string(),
      streamName: z.string(),
      url: z.string(),
    }),
    status: z.string(),
    message: z.string().nullable(),
    additionalCreditCost: z.number().nullable(),
    confidence: z.number().nullable(),
    creditCostAdditionalInfo: z.string(),
    inputsHash: z.string().nullable(),
    runId: z.string().nullable(),
  }),
  taskId: z.string(),
});
export type FindPeopleResult = z.infer<typeof FindPeopleResult>;

export const OPENAI_FIND_PEOPLE_RESULT: FindPeopleResult = {
  result: {
    people: [
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Mira",
        company_first_slug: "thinkingmachinesai",
        last_name: "Murati",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Chief Technology Officer",
        latest_experience_start_date: "2022-05-01",
        location_name: "San Francisco Bay Area, United States",
        name: "Mira Murati",
        profile_id: "upn_871971387",
        url: "https://www.linkedin.com/in/mira-murati-4b39a066/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Fidji",
        company_first_slug: "openai",
        last_name: "Simo",
        latest_experience_company: "OpenAI",
        latest_experience_title: "CEO, Applications",
        latest_experience_start_date: "2025-08-01",
        location_name: "Palo Alto, California, United States",
        name: "Fidji Simo",
        profile_id: "upn_562755096",
        url: "https://www.linkedin.com/in/fidji-simo-90a8982/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Kevin",
        company_first_slug: "openai",
        last_name: "Weil",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Chief Product Officer",
        latest_experience_start_date: "2024-06-01",
        location_name: "Portola Valley, California, United States",
        name: "Kevin Weil",
        profile_id: "upn_135721822",
        url: "https://www.linkedin.com/in/kevin-weil-9202563/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Bret",
        company_first_slug: "openai",
        last_name: "Taylor",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Chairman of the Board",
        latest_experience_start_date: "2023-11-01",
        location_name: "San Francisco, California, United States",
        name: "Bret Taylor",
        profile_id: "upn_792042322",
        url: "https://www.linkedin.com/in/brettaylor/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Srinivas",
        company_first_slug: "openai",
        last_name: "Narayanan",
        latest_experience_company: "OpenAI",
        latest_experience_title: "VP of Applied",
        latest_experience_start_date: "2023-04-01",
        location_name: "San Francisco, California, United States",
        name: "Srinivas Narayanan",
        profile_id: "upn_240732218",
        url: "https://www.linkedin.com/in/srinivas-narayanan-6985b4/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Nick",
        company_first_slug: "openai",
        last_name: "Turley",
        latest_experience_company: "OpenAI",
        latest_experience_title: "VP, Head of ChatGPT",
        latest_experience_start_date: "2022-08-01",
        location_name: "San Francisco, California, United States",
        name: "Nick Turley",
        profile_id: "upn_745619949",
        url: "https://www.linkedin.com/in/nicholas-turley-32b14ab3/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Henry",
        company_first_slug: "cultta",
        last_name: "Jiménez",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Open AI Forum Member",
        latest_experience_start_date: "2025-02-01",
        location_name: "Madrid, Community of Madrid, Spain",
        name: "Henry Jiménez",
        profile_id: "upn_178819098",
        url: "https://www.linkedin.com/in/directorio-de-herramientas-de-inteligencia-artificial-mayor-directorio/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Kate",
        company_first_slug: "openai",
        last_name: "Rouch",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Chief Marketing Officer",
        latest_experience_start_date: "2024-12-01",
        location_name: "San Francisco Bay Area, United States",
        name: "Kate Rouch",
        profile_id: "upn_804672060",
        url: "https://www.linkedin.com/in/katerouch/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Venkat",
        company_first_slug: "openai",
        last_name: "Venkataramani",
        latest_experience_company: "OpenAI",
        latest_experience_title: "VP, App Infra",
        latest_experience_start_date: "2024-06-01",
        location_name: "San Francisco Bay Area",
        name: "Venkat Venkataramani",
        profile_id: "upn_594269473",
        url: "https://www.linkedin.com/in/venkat-venkataramani-0109681/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Sarah",
        company_first_slug: "openai",
        last_name: "Friar",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Chief Financial Officer",
        latest_experience_start_date: "2024-06-01",
        location_name: "San Francisco, California, United States",
        name: "Sarah Friar",
        profile_id: "upn_40228478",
        url: "https://www.linkedin.com/in/sarah-friar/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Margaretta",
        company_first_slug: "margaretta-colangelo-ventures",
        last_name: "Colangelo",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Forum Member",
        latest_experience_start_date: "2024-01-01",
        location_name: "Honolulu, Hawaii, United States",
        name: "Margaretta Colangelo",
        profile_id: "upn_214094733",
        url: "https://www.linkedin.com/in/margarettacolangelo/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Harvey",
        company_first_slug: "53212707",
        last_name: "Castro, MD, MBA.",
        latest_experience_company: "OpenAI",
        latest_experience_title: "OpenAI Forum Member",
        latest_experience_start_date: "2024-02-01",
        location_name: "Dallas-Fort Worth Metroplex",
        name: "Harvey Castro, MD, MBA.",
        profile_id: "upn_685667839",
        url: "https://www.linkedin.com/in/harveycastromd/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Sadie",
        company_first_slug: "hmci-ai",
        last_name: "St Lawrence",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Forum - Community Lead",
        latest_experience_start_date: "2025-01-01",
        location_name: "Sacramento, California, United States",
        name: "Sadie St Lawrence",
        profile_id: "upn_57083144",
        url: "https://www.linkedin.com/in/sadiestlawrence/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Maxime",
        company_first_slug: "paradise-group-com",
        last_name: "Paradis",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Investor",
        latest_experience_start_date: "2024-07-01",
        location_name: "Paris, Île-de-France, France",
        name: "Maxime Paradis",
        profile_id: "upn_769122291",
        url: "https://www.linkedin.com/in/maximeparadis/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Alexandre",
        company_first_slug: "14018249",
        last_name: "Berriche",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Late Stage Investor",
        latest_experience_start_date: "2024-03-01",
        location_name: "Greater Paris Metropolitan Region, France",
        name: "Alexandre Berriche",
        profile_id: "upn_345705256",
        url: "https://www.linkedin.com/in/berriche/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Greg",
        company_first_slug: "openai",
        last_name: "Brockman",
        latest_experience_company: "OpenAI",
        latest_experience_title: "President, Chairman, & Co-Founder",
        latest_experience_start_date: "2015-01-01",
        location_name: "San Francisco, California, United States",
        name: "Greg Brockman",
        profile_id: "upn_611840997",
        url: "https://www.linkedin.com/in/greg-brockman-1599051a/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Leah",
        company_first_slug: "openai",
        last_name: "Belsky",
        latest_experience_company: "OpenAI",
        latest_experience_title: "VP & General Manager, Education",
        latest_experience_start_date: "2024-09-01",
        location_name: "New York, New York, United States",
        name: "Leah Belsky",
        profile_id: "upn_738466610",
        url: "https://www.linkedin.com/in/leahbelsky/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Illai",
        company_first_slug: "gescheit-company",
        last_name: "Gescheit",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Forum Member",
        latest_experience_start_date: "2025-01-01",
        location_name: "United Kingdom",
        name: "Illai Gescheit",
        profile_id: "upn_158280718",
        url: "https://www.linkedin.com/in/illaigescheit/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Elise",
        company_first_slug: "ntan",
        last_name: "Victor, PhD ",
        latest_experience_company: "OpenAI",
        latest_experience_title: "OpenAI Forum Member",
        latest_experience_start_date: "2024-01-01",
        location_name: "Dallas, Texas, United States",
        name: "Elise Victor, PhD",
        profile_id: "upn_198799219",
        url: "https://www.linkedin.com/in/elisecvictor/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Michael",
        company_first_slug: "boringventures",
        last_name: "Bassler",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Investor | Growth Stage",
        latest_experience_start_date: "2024-01-01",
        location_name: "Köln, Nordrhein-Westfalen, Deutschland",
        name: "Michael Bassler",
        profile_id: "upn_644982090",
        url: "https://www.linkedin.com/in/michael-bassler-a1746250/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Nate",
        company_first_slug: "openai",
        last_name: "Gonzalez",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Head of Business Products",
        latest_experience_start_date: "2024-09-01",
        location_name: "San Francisco, California, United States",
        name: "Nate Gonzalez",
        profile_id: "upn_508648560",
        url: "https://www.linkedin.com/in/nate-gonzalez/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Joaquin",
        company_first_slug: "openai",
        last_name: "Quiñonero Candela",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Head of Recruiting",
        latest_experience_start_date: "2025-06-01",
        location_name: "Mountain View, California, United States",
        name: "Joaquin Quiñonero Candela",
        profile_id: "upn_573051794",
        url: "https://www.linkedin.com/in/joaquin-quiñonero-candela-440844/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Perkin",
        company_first_slug: "peoplestrong",
        last_name: "Kothari",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Forum Member",
        latest_experience_start_date: "2024-07-01",
        location_name: "Delhi, India",
        name: "Perkin Kothari",
        profile_id: "upn_621005600",
        url: "https://www.linkedin.com/in/perkinkothari/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Andrew",
        company_first_slug: "iwfm",
        last_name: "Hulbert FIWFM",
        latest_experience_company: "OpenAI",
        latest_experience_title: "AI Prompt Engineer",
        latest_experience_start_date: "2023-01-01",
        location_name: "United Kingdom, United Kingdom",
        name: "Andrew Hulbert FIWFM",
        profile_id: "upn_111262810",
        url: "https://www.linkedin.com/in/andrewhulbert/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Ram Kumar",
        company_first_slug: "14084",
        last_name: "N.",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Forum Member",
        latest_experience_start_date: "2024-11-01",
        location_name: "Plano, Texas, United States",
        name: "Ram Kumar N.",
        profile_id: "upn_234921876",
        url: "https://www.linkedin.com/in/ramkumarnimmakayala/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Jake",
        company_first_slug: "openai",
        last_name: "Fox",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Recruiter",
        latest_experience_start_date: "2023-12-01",
        location_name: "San Francisco, California, United States",
        name: "Jake Fox",
        profile_id: "upn_754753577",
        url: "https://www.linkedin.com/in/jakehfox/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Linden",
        company_first_slug: "openai",
        last_name: "L.",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Research Director",
        latest_experience_start_date: "2022-05-01",
        location_name: "United States",
        name: "Linden L.",
        profile_id: "upn_632671356",
        url: null,
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Ryan",
        company_first_slug: "ryan-staley",
        last_name: "Staley",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Forum Member ",
        latest_experience_start_date: "2024-11-01",
        location_name: "Greater Chicago Area",
        name: "Ryan Staley",
        profile_id: "upn_733440918",
        url: "https://www.linkedin.com/in/ryan-staley-4849323/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Tom",
        company_first_slug: "phantom-iq",
        last_name: "Popomaronis",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Member: OpenAI Forum",
        latest_experience_start_date: "2025-02-01",
        location_name: "Frederick, Maryland, United States",
        name: "Tom Popomaronis",
        profile_id: "upn_499354933",
        url: "https://www.linkedin.com/in/tpopomaronis/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Maggie",
        company_first_slug: "openai",
        last_name: "Hott",
        latest_experience_company: "OpenAI",
        latest_experience_title: "GTM Leadership",
        latest_experience_start_date: "2023-04-01",
        location_name: "San Francisco, California, United States",
        name: "Maggie Hott",
        profile_id: "upn_735493586",
        url: "https://www.linkedin.com/in/maggiehott/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Christian",
        company_first_slug: "headshed",
        last_name: "Facey",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Investor",
        latest_experience_start_date: "2023-12-01",
        location_name: "New York, New York, United States",
        name: "Christian Facey",
        profile_id: "upn_301078350",
        url: "https://www.linkedin.com/in/christian-facey-31795b48/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Shikhar",
        company_first_slug: "openai",
        last_name: "Kwatra",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Partner Solutions Architect",
        latest_experience_start_date: "2024-12-01",
        location_name: "San Francisco, California, United States",
        name: "Shikhar Kwatra",
        profile_id: "upn_728325901",
        url: "https://www.linkedin.com/in/shikharkwatra/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Ismail",
        company_first_slug: "openai",
        last_name: "Zanona",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Member",
        latest_experience_start_date: "2023-08-01",
        location_name: "Riyadh, Saudi Arabia",
        name: "Ismail Zanona",
        profile_id: "upn_617395719",
        url: "https://www.linkedin.com/in/ismail-zanona-and-his-digital-twin/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Arturo",
        company_first_slug: "st--luke%27s-hospital",
        last_name: "LoAIza-Bonilla MD",
        latest_experience_company: "OpenAI",
        latest_experience_title: "AI in Health Member and Contributor",
        latest_experience_start_date: "2024-11-01",
        location_name: "Greater Philadelphia",
        name: "Arturo LoAIza-Bonilla MD",
        profile_id: "upn_777560022",
        url: "https://www.linkedin.com/in/arturoloaizabonillla/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Matt",
        company_first_slug: "greenoaks-capital-partners",
        last_name: "Mochary",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Advisor",
        latest_experience_start_date: "2018-08-01",
        location_name: "San Francisco Bay Area",
        name: "Matt Mochary",
        profile_id: "upn_678207650",
        url: "https://www.linkedin.com/in/matt-mochary-34bb4/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Isa",
        company_first_slug: "openai",
        last_name: "Fulford",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Member of Technical Staff",
        latest_experience_start_date: "2022-01-01",
        location_name: "San Francisco Bay Area",
        name: "Isa Fulford",
        profile_id: "upn_576928738",
        url: "https://www.linkedin.com/in/isabella-fulford/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Melissa",
        company_first_slug: "openai",
        last_name: "Hutchinson",
        latest_experience_company: "OpenAI",
        latest_experience_title:
          "People & Recruiting, Consumer Products in Jackson Square",
        latest_experience_start_date: "2025-07-01",
        location_name: "San Francisco Bay Area",
        name: "Melissa Hutchinson",
        profile_id: "upn_86145726",
        url: "https://www.linkedin.com/in/melissadhutchinson/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Laura",
        company_first_slug: "openai",
        last_name: "Modiano",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Startups EMEA",
        latest_experience_start_date: "2024-09-01",
        location_name: "London, England, United Kingdom",
        name: "Laura Modiano",
        profile_id: "upn_337729769",
        url: "https://www.linkedin.com/in/laura-modiano/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: 'Aaron "Ronnie"',
        company_first_slug: "openai",
        last_name: "Chatterji",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Chief Economist",
        latest_experience_start_date: "2024-11-01",
        location_name: "Durham, North Carolina, United States",
        name: 'Aaron "Ronnie" Chatterji',
        profile_id: "upn_551685248",
        url: "https://www.linkedin.com/in/aaron-ronnie-chatterji-458272/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Zack",
        company_first_slug: "openai",
        last_name: "Kass",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Head of GTM",
        latest_experience_start_date: "2021-01-01",
        location_name: "Santa Barbara, California, United States",
        name: "Zack Kass",
        profile_id: "upn_416012195",
        url: "https://www.linkedin.com/in/zackkass/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Brian",
        company_first_slug: "openai",
        last_name: "Kelleher",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Technical Recruiter",
        latest_experience_start_date: "2023-01-01",
        location_name: "San Francisco, California, United States",
        name: "Brian Kelleher",
        profile_id: "upn_336612951",
        url: "https://www.linkedin.com/in/brian-kelleher-358a7410/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Milos",
        company_first_slug: "global-strategy-group",
        last_name: "Mihajlovic, PhD",
        latest_experience_company: "OpenAI",
        latest_experience_title: "AI Prompt Engineer",
        latest_experience_start_date: "2023-02-01",
        location_name: "Serbia, Serbia",
        name: "Milos Mihajlovic, PhD",
        profile_id: "upn_607230135",
        url: "https://www.linkedin.com/in/milosmihajlovic/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Nicolas",
        company_first_slug: "openai",
        last_name: "Robinson Andrade",
        latest_experience_company: "OpenAI",
        latest_experience_title:
          "Head of Policy - Latin America & the Caribbean",
        latest_experience_start_date: "2024-01-01",
        location_name: "São Paulo e Região",
        name: "Nicolas Robinson Andrade",
        profile_id: "upn_242346444",
        url: "https://www.linkedin.com/in/nicolasrobinsonandrade/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Marco",
        company_first_slug: "marcoandre",
        last_name: "Andre",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Open-AI Forum Member",
        latest_experience_start_date: "2025-02-01",
        location_name: "Zürich Metropolitan Area",
        name: "Marco Andre",
        profile_id: "upn_42136514",
        url: "https://www.linkedin.com/in/marcoandre/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Pragya",
        company_first_slug: "openai",
        last_name: "Misra",
        latest_experience_company: "Openai",
        latest_experience_title: "Lead Public Policy & Partnerships for India",
        latest_experience_start_date: "2024-04-01",
        location_name: "India",
        name: "Pragya Misra",
        profile_id: "upn_568194090",
        url: "https://www.linkedin.com/in/pragya-misra-8948781/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Osvaldo",
        company_first_slug: "center-for-ai-and-digital-policy",
        last_name: "Ramirez Hurtado ",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Global Open AI Forum Member",
        latest_experience_start_date: "2025-02-01",
        location_name: "United States, United States",
        name: "Osvaldo Ramirez Hurtado ",
        profile_id: "upn_722285120",
        url: "https://www.linkedin.com/in/osvaldo-ramirez/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Christian",
        company_first_slug: "guild4ai",
        last_name: "Jumelet ",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Artificial intelligence advisor",
        latest_experience_start_date: "2020-01-01",
        location_name: "Cannes, Provence-Alpes-Côte d’Azur, France",
        name: "Christian Jumelet",
        profile_id: "upn_169085690",
        url: "https://www.linkedin.com/in/christian-jumelet-7ab7501/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Vikram",
        company_first_slug: "the-gtm-circle",
        last_name: "Aditya",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Angel Investor",
        latest_experience_start_date: "2023-10-01",
        location_name: "San Francisco, California, United States",
        name: "Vikram Aditya",
        profile_id: "upn_4345051",
        url: "https://www.linkedin.com/in/viksrum/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Shyamal",
        company_first_slug: "openai",
        last_name: "Anadkat",
        latest_experience_company: "OpenAI",
        latest_experience_title: "Applied AI",
        latest_experience_start_date: "2022-08-01",
        location_name: "San Francisco Bay Area",
        name: "Shyamal Hitesh Anadkat",
        profile_id: "upn_177359998",
        url: "https://www.linkedin.com/in/zostale/",
      },
      {
        company_record_id: null,
        company_table_id: "",
        domain: "openai.com",
        first_name: "Ken",
        company_first_slug: "6226",
        last_name: "Huang",
        latest_experience_company: "OpenAI",
        latest_experience_title: "OpenAI Forum Member",
        latest_experience_start_date: "2024-07-01",
        location_name: "Fairfax, Virginia, United States",
        name: "Ken Huang",
        profile_id: "upn_795929655",
        url: "https://www.linkedin.com/in/kenhuang8/",
      },
    ],
    peopleCount: 4231,
  },
  metadata: {
    textPreview: "Returned 50 Profiles",
    imagePreview:
      "https://clay-base-prod-static.s3.amazonaws.com/icons/svg/person.svg",
    logInfo: {
      requestId: "22e86a17-097e-4f24-beab-63b78f19ba5e",
      groupName:
        "/aws/lambda/ap-e251a70e-46d7-4f3a-b3ef-a211ad3d8bd2-54-prod-20210518175014",
      streamName: "2025/11/06/[$LATEST]2be6b4c3ccc14f2c822c06e4902ee96e",
      url: "https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/ap-e251a70e-46d7-4f3a-b3ef-a211ad3d8bd2-54-prod-20210518175014;stream=2025/11/06/%5B$LATEST%5D2be6b4c3ccc14f2c822c06e4902ee96e;filter=%2222e86a17-097e-4f24-beab-63b78f19ba5e%22;start=1762399788929;end=1762403388929",
    },
    status: "SUCCESS",
    message: null,
    additionalCreditCost: 0,
    confidence: null,
    creditCostAdditionalInfo: "",
    inputsHash: null,
    runId: null,
  },
  taskId: "at_0t5adrpD8gMAjphnQ2A",
};
