import { type z } from "zod";
import { getIconSchema } from "./get-icon-schema";

export const IconIds = [
  "AlignLeft",
  "ArrowElbowRightDown",
  "ArrowsMerge",
  "ArrowUp",
  "At",
  "Briefcase",
  "Buildings",
  "Calendar",
  "Circuitry",
  "Clock",
  "ClockCountdown",
  "Cube",
  "CurrencyDollar",
  "CursorClick",
  "Database",
  "Exam",
  "Eyeglasses",
  "FacebookLogo",
  "FileText",
  "GithubLogo",
  "Globe",
  "GlobeHemisphereWest",
  "GraduationCap",
  "HandCoins",
  "Hash",
  "IdentificationBadge",
  "ImageSquare",
  "InstagramLogo",
  "Link",
  "LinkedinLogo",
  "LinkSimple",
  "MagicWand",
  "MapPin",
  "Medal",
  "Menu",
  "Money",
  "Newspaper",
  "NewspaperClipping",
  "Note",
  "Phone",
  "PiggyBank",
  "ReadCvLogo",
  "Receipt",
  "Robot",
  "SatelliteDish",
  "Stack",
  "Storefront",
  "Sword",
  "Tag",
  "TextT",
  "TreeView",
  "TrendUp",
  "Truck",
  "TwitterLogo",
  "User",
  "UserPlus",
  "Users",
  "UsersThree",
  "Wallet",
  "Wrench",
] as const;

export type IconId = (typeof IconIds)[number];
export const IconIdSchema: z.ZodType<
  IconId,
  z.ZodEffectsDef<z.ZodString>,
  string
> = getIconSchema(IconIds, "icon ID");

export const ClaymationIconIds = [
  "ClaymationSignalsJobChange",
  "ClaymationSignalsJobPostings",
  "ClaymationSignalsNewHire",
  "ClaymationSignalsPromotion",
  "ClaymationSignalsFindNews",
  "ClaymationSignalsCustom",
  "ClaymationLinkedin",
  "ClaymationSignalsDish",
] as const;
export type ClaymationIconId = (typeof ClaymationIconIds)[number];
