import {
  AlignLeft,
  ArrowElbowRightDown,
  ArrowsMerge,
  ArrowUp,
  At,
  Briefcase,
  Buildings,
  Calendar,
  Circuitry,
  Clock,
  ClockCountdown,
  Cube,
  CurrencyDollar,
  CursorClick,
  Database,
  Exam,
  Eyeglasses,
  FacebookLogo,
  FileText,
  GithubLogo,
  Globe,
  GlobeHemisphereWest,
  GraduationCap,
  HandCoins,
  Hash,
  Icon,
  IdentificationBadge,
  ImageSquare,
  InstagramLogo,
  Link,
  LinkedinLogo,
  LinkSimple,
  List,
  MagicWand,
  MapPin,
  Medal,
  Money,
  Newspaper,
  NewspaperClipping,
  Note,
  Phone,
  PiggyBank,
  ReadCvLogo,
  Receipt,
  Robot,
  Stack,
  Storefront,
  Sword,
  Tag,
  TextT,
  TreeView,
  TrendUp,
  Truck,
  TwitterLogo,
  User,
  UserPlus,
  Users,
  UsersThree,
  Wallet,
  Wrench,
} from "@phosphor-icons/react";

import { CustomIconProps } from "@/app/svg/icons/CustomIcons";
import { SatelliteDish } from "@/app/svg/icons/CustomIcons/SatelliteDish";
import { IconId } from "@/shared/icon-ids";

// For use on BE icon mapping to FE icon components
export const PhosphorIconMap: Record<IconId, Icon | React.FC<CustomIconProps>> =
  {
    AlignLeft: AlignLeft,
    ArrowElbowRightDown: ArrowElbowRightDown,
    ArrowsMerge: ArrowsMerge,
    ArrowUp: ArrowUp,
    At: At,
    Briefcase: Briefcase,
    Buildings: Buildings,
    Calendar: Calendar,
    Circuitry: Circuitry,
    Clock: Clock,
    ClockCountdown: ClockCountdown,
    Cube: Cube,
    CursorClick: CursorClick,
    CurrencyDollar: CurrencyDollar,
    Database: Database,
    Exam: Exam,
    Eyeglasses: Eyeglasses,
    FacebookLogo: FacebookLogo,
    FileText: FileText,
    GithubLogo: GithubLogo,
    Globe: Globe,
    GlobeHemisphereWest: GlobeHemisphereWest,
    GraduationCap: GraduationCap,
    HandCoins: HandCoins,
    Hash: Hash,
    IdentificationBadge: IdentificationBadge,
    ImageSquare: ImageSquare,
    InstagramLogo: InstagramLogo,
    Link: Link,
    LinkedinLogo: LinkedinLogo,
    LinkSimple: LinkSimple,
    MagicWand: MagicWand,
    MapPin: MapPin,
    Medal: Medal,
    Menu: List,
    Money: Money,
    Newspaper: Newspaper,
    NewspaperClipping: NewspaperClipping,
    Note: Note,
    Phone: Phone,
    PiggyBank: PiggyBank,
    ReadCvLogo: ReadCvLogo,
    Receipt: Receipt,
    Robot: Robot,
    SatelliteDish: SatelliteDish,
    Stack: Stack,
    Storefront: Storefront,
    Sword: Sword,
    Tag: Tag,
    TextT: TextT,
    TreeView: TreeView,
    TrendUp: TrendUp,
    Truck: Truck,
    TwitterLogo: TwitterLogo,
    User: User,
    UserPlus: UserPlus,
    Users: Users,
    UsersThree: UsersThree,
    Wallet: Wallet,
    Wrench: Wrench,
  };

export default PhosphorIconMap;
